### PR TITLE
Django 1.10 compatibility

### PR DESCRIPTION
**Pull request by ulope**
This updates the imports to be Django 1.10 compatible

Fixes: #4

### CODE REVIEW

**Comment by jmduke** [comment]
Unfortunately this repo looks unmaintained but thanks for this PR.  @ulope would you be interested in maintaining a fork?

**Comment by jmduke** [comment]
Looks like I spoke too soon! Thanks for merging this @aykut!

**Comment by aykut** [comment]
I'm so sorry. I can be busy from time to time and forgot to merge or review PRs and issues.

**Comment by aykut** [comment]
Just pushed the new version to pypi.

Thanks.

**Comment by jmduke** [comment]
Thanks so much for your stewardship of the package (and @ulope for the PR!)  I and many others appreciate the time + effort you spend :)

**Pull request merged**
